language: generic

branches:
  except:
  - staging.tmp
  - trying.tmp


matrix:
  include:
    - os: linux
      sudo: required
      services: docker
      env: myconfig=maxset image=espressomd/docker-ubuntu-18.04:446ff604bbfa63f30ddb462697fa0d0dc2630460

script:
  - maintainer/CI/build_docker.sh
